### ISSUE TITLE
Console error if players got killed

### ISSUE THREAD

**Issue by Ex0ticZero** [sb2bg/CustomDeathMessages#24]
[12:18:25 WARN]: java.lang.NoSuchMethodException: com.mojang.authlib.properties.Property.getName()
[12:18:25 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2259)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//io.github.bananapuncher714.nbteditor.NBTEditor.<clinit>(NBTEditor.java:264)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.chat.ItemSerializer.serializeItemStack(ItemSerializer.java:13)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.chat.HoverTransformers.populateKillWeapon(HoverTransforms.java:66)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.chat.HoverTransformers.lambda$static$2(HoverTransforms.java:43)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.chat.HoverTransformers.transform(HoverTransforms.java:83)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.chat.HoverTransforms.transform(HoverTransforms.java:27)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.chat.DeathMessage.getTextComponent(DeathMessage.java:21)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.listeners.BukkitPlayerDeathListener.setDeathMessage(BukkitPlayerDeathListener.java:70)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.events.CustomPlayerDeathEvent.setDeathMessage(CustomPlayerDeathEvent.java:32)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.listeners.CustomPlayerDeathListener.onPlayerDeath(CustomPlayerDeathListener.java:92)
[12:18:25 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor862.execute(Unknown Source)
[12:18:25 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:18:25 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[12:18:25 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:18:25 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:18:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:18:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[12:18:25 WARN]:        at CustomDeathMessages-2.0.1.jar//org.spartandevs.customdeathmessages.listeners.BukkitPlayerDeathListener.onPlayerDeath(BukkitPlayerDeathListener.java:54)
[12:18:25 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor860.execute(Unknown Source)
[12:18:25 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:18:25 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[12:18:25 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:18:25 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:18:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:18:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[12:18:25 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:984)
[12:18:25 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:963)
[12:18:25 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1560)
[12:18:25 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:973)
[12:18:25 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1132)
[12:18:25 WARN]:        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1326)
[12:18:25 WARN]:        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2183)
[12:18:25 WARN]:        at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2779)
[12:18:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[12:18:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[12:18:25 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2703)
[12:18:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[12:18:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[12:18:25 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[12:18:25 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:18:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:18:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1326)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[12:18:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1303)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1296)
[12:18:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1412)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1158)
[12:18:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:18:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:18:25 INFO]: Ex0ticZero was slain by Apeeeeep using [PEnusuk PAntat]

**Comment by sb2bg** [comment]
This comes from a library I use. I'll check if there are any updates that fix it, if not, I will pass it forward. Can you tell me what server software and version you use please?

**Comment by sb2bg** [comment]
Should be fixed with latest update on Spigot. If not, please leave a comment
