### ISSUE TITLE
On a 1.21 paper server, all the custom death messages work as intended except for PVP death messages.

### ISSUE THREAD

**Issue by ConradwithaK** [sb2bg/CustomDeathMessages#27]
Every time a player kills another player on my server, the death message reads "[victim] was slain by [killer]" even though I added custom death messages to the config file. I also ran it through a YAML linter and it is completely valid code. Again, all the death messages work fine except those which include a %killer% placeholder. It is also worth noting that player heads are not dropping even though I set the drop rate to 75%.

Here is the console error that reads when a player kills another player:

**[01:05:53 ERROR]: Could not pass event CustomPlayerDeathEvent to CustomDeathMessages v2.0.1**
java.lang.ExceptionInInitializerError: null
        at CustomDeathMessages (CDM).69605.jar/org.spartandevs.customdeathmessages.listeners.CustomPlayerDeathListener.getKillWeapon(CustomPlayerDeathListener.java:102) ~[CustomDeathMessages (CDM).69605.jar:?]
        at CustomDeathMessages (CDM).69605.jar/org.spartandevs.customdeathmessages.listeners.CustomPlayerDeathListener.onPlayerDeath(CustomPlayerDeathListener.java:38) ~[CustomDeathMessages (CDM).69605.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at CustomDeathMessages (CDM).69605.jar/org.spartandevs.customdeathmessages.listeners.BukkitPlayerDeathListener.onPlayerDeath(BukkitPlayerDeathListener.java:54) ~[CustomDeathMessages (CDM).69605.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1024) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1038) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1344) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2417) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2796) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2707) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at CustomDeathMessages (CDM).69605.jar/org.spartandevs.customdeathmessages.util.Version.getServerVersion(Version.java:23) ~[CustomDeathMessages (CDM).69605.jar:?]
        at CustomDeathMessages (CDM).69605.jar/org.spartandevs.customdeathmessages.util.Version.<clinit>(Version.java:20) ~[CustomDeathMessages (CDM).69605.jar:?]
        ... 45 more

**Comment by arrxa** [comment]
Please tell me you found a fix for this issue I'm having the exact same problem.

**Comment by sb2bg** [comment]
Fixed with latest update on Spigot!
